- name: Pull Image
  docker_image:
    name: "{{ container_image }}"
    source: pull


- name: Create Container for the image
  docker_container:
    name: "{{ container_name }}{{ item }}"
    image: "{{ container_image }}"
    pull: true
    state: started
    restart_policy: always
    ports:
    - "3000:3000"
    env:
     MONGO_URI: "mongodb://172.31.29.194"
  with_sequence: count=1
