- name: Pull Image
  docker_image:
    name: "{{ container_image }}"
    source: pull


- name: Create Container for the image
  docker_container:
    name: "{{ container_name }}{{ item }}"
    image: "{{ container_image }}"
    state: present
  with_sequence: count=1